import { Platform, StyleSheet } from 'react-native';

export const stickersStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#05110B',
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  scrollContent: {
    paddingBottom: 40,
    gap: 16,
  },
  // Top Header (if page-level or custom)
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#102A1C',
    marginBottom: 8,
  },
  headerMenuBtn: {
    padding: 8,
  },
  headerMenuText: {
    color: '#4ADE80',
    fontSize: 24,
    fontWeight: 'bold',
  },
  headerTitle: {
    color: '#4ADE80',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 1.5,
    fontFamily: Platform.OS === 'ios' ? 'Helvetica Neue' : 'sans-serif-condensed',
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#1E293B',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4ADE80',
    overflow: 'hidden',
  },
  avatarImg: {
    width: '100%',
    height: '100%',
  },

  // Card: Minha Coleção
  collectionCard: {
    backgroundColor: '#0A1C13',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#133021',
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  collectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 12,
  },
  collectionTitleLabel: {
    color: '#8CA185',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  collectionProgressText: {
    color: '#4ADE80',
    fontSize: 20,
    fontWeight: '800',
    marginTop: 2,
  },
  collectionCountText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  progressBarContainer: {
    height: 8,
    backgroundColor: '#12281D',
    borderRadius: 4,
    width: '100%',
    overflow: 'hidden',
    marginBottom: 16,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#4ADE80',
    borderRadius: 4,
  },
  collectionButtonsContainer: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  scanButton: {
    flex: 1,
    backgroundColor: '#FACC15',
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 6,
  },
  scanButtonText: {
    color: '#05110B',
    fontSize: 12,
    fontWeight: '800',
  },
  openCollectionButton: {
    flex: 1.2,
    backgroundColor: '#102A1C',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#183B27',
  },
  openCollectionButtonText: {
    color: '#E2E8F0',
    fontSize: 12,
    fontWeight: '700',
  },

  // Card: Rasgue o seu Pacote
  ripCardContainer: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  ripCardGradient: {
    paddingVertical: 28,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ripCardText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0.5,
    flex: 1,
  },
  ripCardIconContainer: {
    marginLeft: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    padding: 10,
    borderRadius: 12,
  },

  // Card: Pacote Lendário (Oferta Limitada)
  promoCard: {
    backgroundColor: '#FACC15',
    borderRadius: 16,
    padding: 20,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  promoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  promoBadgeText: {
    color: '#05110B',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  promoTitle: {
    color: '#05110B',
    fontSize: 28,
    fontWeight: '900',
    marginBottom: 4,
  },
  promoSubtitle: {
    color: '#1E293B',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 16,
    maxWidth: '75%',
  },
  buyButton: {
    backgroundColor: '#05110B',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignSelf: 'flex-start',
  },
  buyButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  promoGraphicsContainer: {
    position: 'absolute',
    right: -10,
    bottom: -15,
    opacity: 0.8,
  },
  promoGraphicCard1: {
    width: 60,
    height: 90,
    backgroundColor: 'rgba(5, 17, 11, 0.15)',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#05110B',
    transform: [{ rotate: '15deg' }],
    position: 'absolute',
    right: 20,
    bottom: 20,
  },
  promoGraphicCard2: {
    width: 60,
    height: 90,
    backgroundColor: 'rgba(5, 17, 11, 0.1)',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#05110B',
    transform: [{ rotate: '35deg' }],
    position: 'absolute',
    right: 5,
    bottom: 10,
  },

  // Card: Faltam para Você
  missingCard: {
    backgroundColor: '#0A1C13',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#133021',
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  missingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  missingTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  missingRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#12281D',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  missingBadgeText: {
    color: '#8CA185',
    fontSize: 12,
    fontWeight: '700',
  },
  missingChevron: {
    color: '#8CA185',
    fontSize: 10,
    fontWeight: 'bold',
  },

  // Ripping animation modal or feedback
  rippingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(5, 17, 11, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  rippingText: {
    color: '#4ADE80',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 16,
  },
  rippedStickerContainer: {
    alignItems: 'center',
    padding: 24,
  },
  rippedStickerTitle: {
    color: '#FFFFFF',
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 20,
    textAlign: 'center',
  },
  stickersRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  stickerRevealCard: {
    width: 90,
    height: 130,
    backgroundColor: '#0F2C1D',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FACC15',
    justifyContent: 'space-between',
    padding: 8,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 6,
  },
  stickerRevealFlag: {
    fontSize: 20,
  },
  stickerRevealName: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  stickerRevealGroup: {
    color: '#FACC15',
    fontSize: 8,
    fontWeight: 'bold',
  },
  closeRevealBtn: {
    backgroundColor: '#FACC15',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  closeRevealBtnText: {
    color: '#05110B',
    fontSize: 14,
    fontWeight: '800',
  },
});
